<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit163a55200a31bb76e7c883f3eaba25b2
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TYPO3Fluid\\Fluid\\' => 17,
        ),
        'P' => 
        array (
            'Pabisch\\Balls\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TYPO3Fluid\\Fluid\\' => 
        array (
            0 => __DIR__ . '/..' . '/typo3fluid/fluid/src',
        ),
        'Pabisch\\Balls\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit163a55200a31bb76e7c883f3eaba25b2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit163a55200a31bb76e7c883f3eaba25b2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
